### ISSUE TITLE
Problem combining multiple middlewares

### ISSUE THREAD

**Issue by prolic** [prooph/http-middleware#12]
If you want to pipe multiple query middlewares, it's not possible to use the provided query middleware, because you can only set one `NAME_ATTRIBUTE`. Another possibility is, to define multiple query middlewares (one for each query). One that gets this attribute passed into constructor, rather then as request attribute. The problem however with this approach is, that
1) You have to create lots of config boilerplate
2) The application will need to construct multiple middleware instances, instead of being able to reuse an existing one.

Any ideas how we can improve this?

/cc @codeliner @sandrokeil @basz @oqq

**Comment by basz** [comment]
Can you explain how and when you need pipe multiple queries? I'm not seeing when that would be useful.

**Comment by prolic** [comment]
F.e. You pipe through 2 query middlewares and then you pipe to a view middleware, that should display the results of both queries. So it's really only the case, when building the frontend itself in PHP, too. Not for pure API's.

**Comment by oqq** [comment]
This would not answer your question, but some throughs:

The main issue on this is the piping of multiple query middlewares. I have done this in a project and i hate this every second. (You know what I mean @prolic)

My queries always response with an array containing at least one key which identifies the requested resource. The query middleware than creates an object which would be merge this arrays to one response. So this is really easy to implement.

But this would not work for every read model implementation of course.

Ah and yes.. I have to create an instance of that middleware for every query, what is not so neat.
This could be done by something like an URI to query resolver. Or a request parameter to query resolver.

```php
'https://api.acme.com/query/{query_name}' => function ($request) {
$query = $this->queryResolver($request->getAttribute('query_name'));
}
```

**Comment by oqq** [comment]
Maybe we should split this concerns. A query middleware which responses for api requests, and a view middleware, which resolves more than one query to fulfill view parameters.

One point to consider: using contents from one query result for another query.

That is not a simple task (have a look at graph api)

I would like have something like this:
result for query 1:
```json
{
    "name": "fuubar",
    "subcontents": [UUID, UUID]
}
```

query 2:
resolve UUIDs and enrich the result


Some can arg that I have to create a read model which contains ALL sub contents at once. But I have this already done in a project and this is a really messy task at some point.


My throughs about that:
We can build something like https://docs.zendframework.com/zend-expressive-hal/.

- A query result can have links to other resources.
- If the resolver was requested to resolve also all links, than all other resources would be "embedded"

Every view has its own resolver definition and can contain multiple DomainQuery.

**Comment by basz** [comment]
I guess it would be possible with some sort of stack for NAME_ATTRIBUTE, that should all resolve...

Not sure if this is possible (is. the attribute set on the request just before the middelware is executed?) but this might work. What if you introduce a new attribute QueryMiddleware::STACK_NAME_ATTRIBUTE. When that is set on the request, it pushes it to NAME_ATTRIBUTE (stack) reqeust and forward to the handler until STACK_NAME_ATTRIBUTE is not given.

An outer QueryMiddleware would then be required to resolve each given query on NAME_ATTRIBUTE

**Comment by basz** [comment]
> We can build something like https://docs.zendframework.com/zend-expressive-hal/.

or: https://github.com/neomerx/json-api
or ,... is this a prooph concern?

**Comment by oqq** [comment]
@basz i would connect to the "embedded" and "links" feature and how they resolve this, not to "we should use json/hal". The result of such a view middleware should not use json at all, since mostly all template renderer uses arrays for parameters.

**Comment by camuthig** [comment]
What about restructuring the supported request to look more like an array of messages? Currently the JSON would be something like 

```
{
  "prooph_query_name": "my_query",
  "filter1": "stuff",
  "filter2": "other stuff"
}
```

If you instead made it an array, with each object holding a `message_name` and `payload`

```
[
  {
    "message_name": "my_query",
    "payload": {
      "filter1": "stuff",
      "filter2": "other stuff"
    }
  }
]
```

then your single middleware could handle each of the requests. You could use the same structure, maybe supporting an array of objects or not, for each middleware, giving each one a more consistent format as well.

**Comment by prolic** [comment]
Sounds good @camuthig - wanna submit a PR?

**Comment by camuthig** [comment]
I'll see what I can get done this weekend, sure.

**Comment by Orkin** [comment]
Maybe this issue can be closed ?
